//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.UserOrderedBooks = new HashSet<UserOrderedBook>();
        }
    
        public int bookId { get; set; }
        public string bookTitle { get; set; }
        public string bookDiscription { get; set; }
        public string bookImage { get; set; }
        public string bookPrice { get; set; }
        public int bookQuantity { get; set; }
        public string bookAuthorName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOrderedBook> UserOrderedBooks { get; set; }
    }
}
